steps:
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - 'https://github.com/bikalfm/CliniqChatBot.git'
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}'
  - name: gcr.io/cloud-builders/kubectl
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
    args:
      - set
      - image
      - 'deployment/${_DEPLOYMENTNAME}'
      - '${_CONTAINERNAME}=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}'
      
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
  
substitutions:
  _GKE_CLUSTER: cliniqcluster
  _DEPLOYMENTNAME: cliniq-service
  _CONTAINERNAME: cliniq-service
  _REPO_NAME: cicd-service
  _VERSION: v1.0
  _PROJECT: cliniqdocsummarizer
  _ZONE: us-central1
