steps:
#First Clone from Google Cloud Source Repository  
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://github.com/bikalfm/CliniqChatBot.git']

#Build the image 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}','./simple-ai-chatbot-main/']

#Push the image  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']
  
#Update the container image using kubectl set
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/${_DEPLOYMENTNAME}'
  - '${_CONTAINERNAME}=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
  
substitutions:
    #GCP Specific configuration. Please DON'T change anything
    _PROJECT: cliniqdocsummarizer
    _ZONE: us-central1
    _GKE_CLUSTER: cliniqcluster
    
    #Repository Specific configuration. DevOps can change this settings
    _DEPLOYMENTNAME: cliniq-service
    _CONTAINERNAME: cliniq-service    
    _REPO_NAME: cicd-service
    
    # Developers ONLY change
    _VERSION: v1.0
    
options:
    substitution_option: 'ALLOW_LOOSE'
